# Generated by Django 5.1.7 on 2025-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField()),
                ('likelihood', models.FloatField()),
                ('relevance', models.FloatField()),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('topics', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('pest', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('swot', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
    ]
